### PR TITLE
Made a swipe function and app can be completely finished.

### PR DESCRIPTION
**Pull request by saechimdaeki**
What about this direction? 
I created the up, down, left, and right swipe functions and changed the talking buttons simply. Wouldn't it be able to do more using the swipe function . like make edittext null.

First of all, I can check that each function is working well through Toast_Message.

### CODE REVIEW

**Comment by saechimdaeki** [comment]
like this 
design

**Comment by saechimdaeki** [comment]
@NachiketaVadera 
Now you can press the back button twice to completely shut down the app.
Press the Backward button once and then press it again within 2 seconds.

this is latest test :

completly

**Comment by NachiketaVadera** [comment]
@saechimdaeki Thank your for your interest! Looks like you've made cool new improvements and also managed to give me idea about new ones I can make.

**Comment by saechimdaeki** [comment]
@NachiketaVadera Thank you for accepting my opinion!

**Pull request merged**
